<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
var menus = [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"党员",
                        "menuJump":"列表",
                        "tableName":"dangyuan"
                    },
					{
					    "buttons":[
					        "新增",
					        "查看",
					        "修改",
					        "删除"
					    ],
					    "menu":"党费登记",
					    "menuJump":"列表",
					    "tableName":"dangfeidengji"
					},
					{
					    "buttons":[
					        "新增",
					        "查看",
					        "修改",
					        "删除"
					    ],
					    "menu":"奖惩记录",
					    "menuJump":"列表",
					    "tableName":"jiangchengjilu"
					}
                ],
                "menu":"党员管理"
            },
            
            
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"支部",
                        "menuJump":"列表",
                        "tableName":"zhibu"
                    },
					{
					    "buttons":[
					        "新增",
					        "查看",
					        "修改",
					        "删除"
					    ],
					    "menu":"基层单位",
					    "menuJump":"列表",
					    "tableName":"jicengdanwei"
					},
					{
					    "buttons":[
					        "新增",
					        "查看",
					        "修改",
					        "删除"
					    ],
					    "menu":"支部荣誉",
					    "menuJump":"列表",
					    "tableName":"zhiburongyu"
					}
                ],
                "menu":"支部管理"
            },
            
            
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"支部日志",
                        "menuJump":"列表",
                        "tableName":"zhiburizhi"
                    }
                ],
                "menu":"支部日志"
            },
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告信息",
                        "menuJump":"列表",
                        "tableName":"xitonggonggao"
                    }
                ],
                "menu":"公告管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    },
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "支付"
                        ],
                        "menu":"党费缴纳",
                        "menuJump":"列表",
                        "tableName":"dangfeidengji"
                    }
                ],
                "menu":"党费缴纳"
            },
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"奖惩记录",
                        "menuJump":"列表",
                        "tableName":"jiangchengjilu"
                    }
                ],
                "menu":"奖惩记录"
            },
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"公告信息",
                        "menuJump":"列表",
                        "tableName":"xitonggonggao"
                    }
                ],
                "menu":"公告信息"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"党员",
        "tableName":"dangyuan"
    },
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"党员",
                        "menuJump":"列表",
                        "tableName":"dangyuan"
                    },
					{
					    "buttons":[
					        "新增",
					        "查看",
					        "修改",
					        "删除"
					    ],
					    "menu":"党费登记",
					    "menuJump":"列表",
					    "tableName":"dangfeidengji"
					},
					{
					    "buttons":[
					        "新增",
					        "查看",
					        "修改",
					        "删除"
					    ],
					    "menu":"奖惩记录",
					    "menuJump":"列表",
					    "tableName":"jiangchengjilu"
					}
                ],
                "menu":"党员管理"
            },
            
            
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"基层单位",
                        "menuJump":"列表",
                        "tableName":"jicengdanwei"
                    },
					{
					    "buttons":[
					        "查看",
					        "修改",
					        "删除"
					    ],
					    "menu":"支部荣誉",
					    "menuJump":"列表",
					    "tableName":"zhiburongyu"
					}
                ],
                "menu":"支部管理"
            },
            
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"支部日志",
                        "menuJump":"列表",
                        "tableName":"zhiburizhi"
                    }
                ],
                "menu":"支部日志"
            },
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"公告信息",
                        "menuJump":"列表",
                        "tableName":"xitonggonggao"
                    }
                ],
                "menu":"公告信息"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"支部",
        "tableName":"zhibu"
    }
];

var hasMessage = '';
